<a href="https://colab.research.google.com/github/aysahoo/Learning-Pytorch/blob/main/tensors_in_pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print("GPU is available.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available. Using CPU")

GPU is available.
Using GPU: Tesla T4


In [ ]:
a = torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.rand(3,4)

tensor([[0.1266, 0.7393, 0.2731, 0.1030],
        [0.2335, 0.0697, 0.6104, 0.6377],
        [0.0014, 0.7202, 0.9965, 0.5190]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

# Tensor Shapes


In [ ]:
x = torch.tensor([[1,2,3],[2,3,4]])
x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 7306304486075740721]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

# Tensor Data Type

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
x.to(dtype = torch.float64)

tensor([[1., 2., 3.],
        [2., 3., 4.]], dtype=torch.float64)

# Mathematical Operations

In [ ]:
#Scalar Operation
x = torch.rand(2,2)
x

tensor([[0.1217, 0.7356],
        [0.7118, 0.7876]])

In [ ]:
x+2

tensor([[2.1217, 2.7356],
        [2.7118, 2.7876]])

In [ ]:
x-1

tensor([[-0.8783, -0.2644],
        [-0.2882, -0.2124]])

In [ ]:
x**2

tensor([[0.0148, 0.5411],
        [0.5066, 0.6203]])

In [ ]:
c = torch.tensor([1,-2,3,4,5])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4, 5])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3, -4, -5])

In [ ]:
torch.clamp(c, min = 1, max = 3)

tensor([1, 1, 3, 3, 3])

In [ ]:
e = torch.randint(size = (2,3), low=1, high = 10, dtype=torch.float32)
e

tensor([[7., 9., 3.],
        [7., 7., 4.]])

In [ ]:
torch.sum(e)

tensor(22)

In [ ]:
torch.sum(e, dim=0)


tensor([ 3,  8, 11])

In [ ]:
torch.sum (e, dim =1)

tensor([15,  7])

In [ ]:
torch.mean(e)

tensor(6.1667)

In [ ]:
torch.median(e)

tensor(7.)

In [ ]:
torch.prod(e)

tensor(37044.)

In [ ]:
torch.std(e)

tensor(2.2286)

In [ ]:
torch.var(e)

tensor(4.9667)

In [ ]:
torch.argmax(e)

tensor(1)

In [ ]:
torch.argmin(e)

tensor(2)

In [ ]:
c = torch.tensor([1,-2,3,4,5])
c

tensor([ 1, -2,  3,  4,  5])

# Special Function

In [ ]:
k = torch.randint(size = (2,3), low = 2, high = 10, dtype = torch.float32)
k

tensor([[7., 8., 5.],
        [6., 7., 8.]])

In [ ]:
torch.log(k)

tensor([[1.9459, 2.0794, 1.6094],
        [1.7918, 1.9459, 2.0794]])

In [ ]:
torch.exp(k)

tensor([[1096.6332, 2980.9580,  148.4132],
        [ 403.4288, 1096.6332, 2980.9580]])

In [ ]:
torch.sqrt(k)

tensor([[2.6458, 2.8284, 2.2361],
        [2.4495, 2.6458, 2.8284]])

In [ ]:
torch.sigmoid(k)

tensor([[0.9991, 0.9997, 0.9933],
        [0.9975, 0.9991, 0.9997]])

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.6487, 0.3076, 0.4217],
        [0.7527, 0.0428, 0.0950]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.6487, 0.3076, 0.4217],
        [0.7527, 0.0428, 0.0950]])

# Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
torch.rand((2,3), device = device)

tensor([[0.2276, 0.6734, 0.8309],
        [0.6736, 0.8428, 0.0286]], device='cuda:0')

In [ ]:
a

tensor([[0.6487, 0.3076, 0.4217],
        [0.7527, 0.0428, 0.0950]])

In [ ]:
c = a.to(device)

In [ ]:
c+5

tensor([[5.6487, 5.3076, 5.4217],
        [5.7527, 5.0428, 5.0950]], device='cuda:0')